---
name: '🚀 Deploy Call'
on:
  push:
    branches: [ main ]
    tags: ['v*.*.*']
  workflow_dispatch:

jobs:
  deploy:
    name: '🚀 Deploy'
    uses: z-shell/.github/.github/workflows/deploy-call.yml@main
    secrets:
#      deploy_key: ''
      personal_token: ${{ secrets.GH_PAT }}
    with:
#     external_repository: ''
#     publish_branch: ''
#     publish_dir: ''
#     destination_dir: ''
#     cname: ''
     keep_files: true
     allow_empty_commit: true
